data_assumption_caution_tab <- function() {
  div(
    class = "container mw-100 px-5",
    tabPanel(
      "Data Sources, Assumptions & Cautions",
      value = "data_sources",
      tabsetPanel(
        tabPanel("Background",
          class = "overflow-auto",
          style = "height: calc(100vh - 160px)",
          column(6,
            h1("Background"),
            h2("The Need for a Cost Benefit Tool"),
            tags$p("Given the substantial current and future threat of vector-borne diseases, novel biotechnological innovations have been developed in which mosquitoes, biologically modified to alter disease transmission, are released to suppress or replace existing mosquito species. ",
            "Examples of interventions include Wolbachia, a naturally occurring endosymbiotic bacteria, has been shown to compete with viruses such as dengue, and newer developments such as gene drive which aim to produce genetically modified Anopheles mosquitoes that pass genetic modifications to their offspring, reducing the number of female mosquitoes which can cause malaria."),
            tags$p("Despite numerous promising studies of mosquito-release interventions, what is not known to date is how to best implement a mosquito-targeted approach at scale across technologies, diseases, and geographies."),
            tags$p("Without evidence on the estimated costs and benefits of such interventions, there is a risk that mosquito release programs will not be implemented in areas where there is the greatest need and potentially the greatest payoff for the investment."),
            tags$p("This knowledge gap has been addressed by the development of this cost-benefit tool which is critical for interventions that are already established (e.g., Wolbachia) as they expand to new geographies, and for new interventions that are likely to be implemented in the future."),
            tags$p("The tool includes Brazil, Colombia, Indonesia, Mexico, Sri Lanka, and Vietnam as geographies where technologies for preventing dengue could be implemented and scaled up. Burkina Faso is included in this tool as a demonstration of how this tool might be utilized for future technologies (e.g., gene drive) for malaria control. As such, many of the estimates and assumptions, particularly around cost, are uncertain for the malaria application."),
            tags$p("This tool provides insight into cutting-edge scientific advancements that will be implemented by policymakers with the backing of local constituents. As such, the data need to be freely accessible and understandable to non-experts."),
            tags$p("These estimates will be imperfect, and significant limitations should be taken into consideration prior to use. However, we still believe that this provides a starting point for important conversations on costs and benefits that have not previously been available."),
            br()
          )
        ),
        tabPanel("Primary Input Parameters",
          class = "overflow-auto",
          style = "height: calc(100vh - 160px)",
          column(6,
            # h1("Input Parameters:"),
            h2("Primary Input Parameters"),
            h3("Cost Inputs"),
            tags$p("Costs have been generalized to a number of common program phases which include planning, preparation, production, distribution, release, and monitoring."),
            tags$p("Planning refers to creating a coordinated release plan using data sources for geospatial disease burden, population demographics, health systems costing, environmental covariates, and vector bionomics. Preparation refers to regulatory and stakeholder engagement logistics such as Environmental Impact Assessments, social mobilization, and setting up procurement agreements. Production refers to building or leasing an appropriate facility, training staff, and rearing a breeding line of mass-produced mosquitos. Distribution refers to Sex-sorting followed by transportation to release areas via ground or air shipping. Release refers to the release of live adults or placement of eggs along pre-determined release grid to cover maximum relevant program area. Monitoring refers to three types of monitoring: environmental monitoring to ensure no unplanned effects on relevant ecological niches; entomological monitoring to determine intervention establishment in local vectors; epidemiological monitoring to measure impact on human disease in target areas for determining effectiveness. "),
            tags$p("Cost data for mosquito release technologies are not publicly shared by implementers. Publicly available information (e.g., in academic and grey literature) varies drastically. Based on budget estimates, publicly available literature, and key informant interviews, costs were aggregated to the program category and averaged to determine a range for each category for Aedes and Anopheles mosquitoes."), 
            tags$p("It is important to note that these are estimates, which are very likely to change drastically over time, particularly for new technologies (e.g., gene drive) which do not currently have field trials from which to estimate costs."),
            br(),
            h3( "Cost Limitations "), 
            tags$p("All costs are presented as high level estimates, as a cost per kilometer squared by program phase."), 
            tags$p("Costs were not adjusted for program phase (e.g., earlier programs may have higher preparation/planning costs than later stages would). However, the user can adjust these values manually."), 
            tags$p("Given Anopheles programs have not been implemented widely, the costs are theoretical. Costs for Anopheles are assumed to be significantly higher than dengue costs due to rearing difficulties and the need to release in rural areas. The high-cost scenario for Aedes was assumed to be the low cost for Anopheles."),
            tags$p("These estimates will likely decrease substantially over time given gene drive is self-sustaining and would not require repeated releases throughout a program. As field trials are conducted and the costs are d efined, the tool will be refined to include these updated values."),
            br()
          )
        ),
        tabPanel("Secondary Input Parameters",
          class = "overflow-auto",
          style = "height: calc(100vh - 160px)",
          column(6,
            h2("Secondary Input Parameters"),
            h3("Burden"),
            "We relied on modelled raster data for burden as asymptomatic and symptomatic dengue and malaria are severely underreported. Dengue burden was from",
            tags$a(href="https://www.nature.com/articles/nature12060", "Bhatt et al. 2013"),
            "Malaria burden was from",
            tags$a(href="http://malariaatlas.org/", "The Malaria Atlas Project"),
            "To calculate the number of cases, we relied on incidence adjusted by the population size in each geography. For Burkina Faso, we also included prevalence for each geography as this was used as a cut-off to determine relevant program areas.",
            br(),
            h3("Burden Limitations"), 
            "Burden estimates do not reflect reported cases of disease in each geography, and are rather modelled, which may be subject to issues relating to quality of input data and model parameterization. However, this was necessary given that both diseases are underreported and not systematically collected across countries.", 
            br(), br(),
            h3( "Morbidity & Mortality"), 
            "We relied on national estimates of Disability Adjusted Life Years (DALYs) and deaths for each country from", 
            tags$a(href = "http://www.healthdata.org/gbd/2019 ",  
                  "Institute for Health Metrics and Evaluation (IHME)"), ". The user can input the mortality rate in the tool based on their own knowledge or literature for the relevant geography rather than relying on our national estimates.",
            tags$ul(
              tags$li("Dengue in Indonesia: DALYs: 47,505; Mortality Rate: 0.0038 "),
              tags$li("Malaria in Burkina Faso: 1,962,641 DALYs; Mortality Rate: 0.0038 "),
              tags$li("Dengue in Vietnam: 16,786 DALYs; Mortality Rate: 0.0001 "),
              tags$li("Dengue in Brazil: 40,600 DALYs; Mortality Rate: 0.0002"),
              tags$li("Dengue in Sri Lanka: 18,138 DALYs; Mortality Rate: 0.001 "),
              tags$li("Dengue in Mexico: 10,462 DALYs; Mortality Rate: 9.47E-05 "),
              tags$li("Dengue in Colombia: 24,592 DALYs; Mortality Rate: 0.0009 ")
            ),
            br(),
            h3( "Morbidity & Mortality Limitations "), 
            "IHME country-level statistics were used which may mask heterogeneity in morbidity and mortality at the district level ", 
            br(), br(), 
            h3( "Administrative Divisions "), 
            "Administrative division rasters come from ", 
            (tags$a(href = "https://gadm.org/",  "GADM")),
            "Administrative divisions are organized from the largest (ADM0) to the smallest geographic units (ADM3 or ADM2, depending on the country).",
            br(), br(), 
            h3("Population"),
            "Population rasters were accessed from ", 
            (tags$a(href = "https://www.worldpop.org/ ",  "WorldPop")), 
            "The preferred format is Unconstrained 30 arc (approximately 1km at the equator) resolution raster estimates of population density, adjusted to match UN Population estimates and measured in units of persons per kilometer squared. ", 
            br(), br(), 
            h3("Effectiveness"),
            "Effectiveness is included as a user-input value in the cost-benefit tool where a user can select 0-100% effective.",
            (tags$a(href = "https://www.nejm.org/doi/full/10.1056/NEJMoa2030243",  "A recent randomized trial of Wolbachia in Yogyakarta(Utarini et al. 2021)")), "demonstrated 77% (95% CI: 65-85) reduction in dengue incidence.",
            "There are no estimates for gene drive as it is earlier in the development process.", 
            br(), br(),
            h3( "Healthcare Utilization, Cost of Illness, & Cost of Death "),
            "To quantify health system and economic costs, we relied on estimates for percentage of cases treated in an ambulatory and hospitalized setting, the associated costs with each visit, and the economic losses associated with a death from ", 
            (tags$a(href = "https://pubmed.ncbi.nlm.nih.gov/27091092/ ",  "Shepard et al. 2016")), 
            br(),br(),
            "The user can input their own estimates for ambulatory, hospitalized, and economic costs and healthcare utilization into the tool rather than relying on our estimates.",
            "Estimates for the percent treated in an ambulatory setting and associated cost per ambulatory visit are as follows: ",
            tags$ul(
              tags$li("Indonesia, 44.86%, USD 53"),
              tags$li("Burkina Faso 83.80%, USD 8"),
              tags$li("Vietnam 75.79%, USD 23"),
              tags$li("Brazil 75.94%, USD 58"),
              tags$li("Sri Lanka 57.07%, USD 51"),
              tags$li("Mexico 63.70%, USD 350"),
              tags$li("Colombia 69.61% USD 102")
            ),
            br(),
            "Estimates for the percentage of hospitalized visits and associated costs of those visits are as follows: ", 
            tags$ul(
              tags$li("Indonesia, 34.51%, USD 328"),
              tags$li("Burkina Faso 16.20%, USD 15"),
              tags$li("Vietnam 17.12%, USD 67"),
              tags$li("Brazil 3.26%, USD 376"),
              tags$li("Sri Lanka 17.55%, USD 307"),
              tags$li("Mexico 10.13%, USD 1,201"),
              tags$li("Colombia 3.79% , USD 620")
            ),
            br(),
            "The economic costs associated with a dengue/malaria death were estimated using a human capital approach and are as follows for a child mortality (2016 USD):", 
            tags$ul(
              tags$li("Indonesia USD 100,000"),
              tags$li("Burkina Faso USD 20,000"),
              tags$li("Vietnam USD 55,000"),
              tags$li("Brazil USD 323,000"),
              tags$li("Sri Lanka USD 95,000"),
              tags$li("Mexico USD 297,000"),
              tags$li("Colombia USD 226,000"),
            ),
            br(),
            h3( "Healthcare Utilization, Cost of Illness, & Cost of Death Limitations "),
            "Given mosquitoes for dengue control were our primary focus (6/7 countries included) we relied on estimates for healthcare utilization for dengue and cost of illness/death associated with dengue and applied this for malaria. This may be a limitation given that malaria deaths tend to occur at different ages (primarily in <5s) than dengue. Another key limitation is that dollar estimates have not been adjusted to present value (2021). Lastly, as we did not age-disaggregate cases in the tool, we assumed all deaths were from children, which may have overestimated the overall economic losses associated with the disease.",
            br(), br()
          )
        ),
        tabPanel("Decisions & Calculations",
          class = "overflow-auto",
          style = "height: calc(100vh - 160px)",
          column(6,
            h2( "Decisions & Calculations ") ,
            h3( "Relevant Target Areas for Malaria "),
            "Given malaria vectors (Anopheles gambiae and Anopheles albopictus) are primarily distributed among rural areas, mosquito release programs for malaria would likely occur in areas where traditional control are insufficient. Target areas were restricted to overlap between areas designated as rural and where the malaria prevalence was high, which were where population Density: 1< Persons per KM squared <300, malaria burden determined by Plasmodium falciparum prevalence > 0.35*. These cut offs were determined by inputs from experts and through the definitions of the WHO. ", 
            br(), br(), 
            h3( "Relevant Target Areas for Dengue "),
            "Programs likely to be implemented on the level of the smallest administrative area (and neighborhoods/villages within those areas. Dengue, target areas were restricted to urban areas (Population Density > 1000 persons per km2*). Population density cut offs were based on input from experts. Intervention is only implemented in residential areas, excluding parks, vegetation, industrial zones, etc. would mean ~80% of the cities would be covered by programs. ", 
            br(), br(),
            h3("Relevant Areas Limitation"),
            "There are a few limitations of note related to the relevant areas. For dengue, there is no minimum incidence threshold. This may result in some issues with the estimates, as the tool may recommend scaling up to urban areas where dengue is not be found (e.g., due to elevation or other factors). For malaria, given that we are estimating costs and scale up per kilometer squared, it is likely these areas are overestimated. Mosquitoes would likely only be released in a small portion of each relevant area. Relatedly, QGIS Zonal Statistics function (which was used to calculate the relevant area) works imperfectly. There were ~60/10,000 districts identified errors in Brazil and ~70/7,000 districts identified errors in Indonesia. Visual pixel approximations were utilized where errors were identified.",
            br(), br()
          )
        )
      )
    )
  )
}
