user_guide_tab <- function() {
  tabPanel("User Guide",
    img(src='START_306_logo.png', align = "center", height = "60px"),
    br(), br(),
    column(6,
      h1("Welcome"),
      "This tool was developed by the Strategic Analysis, Research & Training (START) Center in the Department of Global Health at the University of Washington. The purpose of this tool is to summarize the costs and benefits of existing and new mosquito release programs across geographic settings and disease contexts.",
      br(), br(),
      img(src = "mosquito.png", width = "350px"),
      br(),
      h1("Acknowledgements"),
      "Thank you to all of our collaborators:",
      br(),
      div(img(src = "acknowledgements.png", width = "100%"))
    ),
    column(6,
      h1("Instructions for Use"),
      "1) ",
      strong("select your country of interest"),
      br(),
      "Brazil, Colombia, Indonesia, Mexico, Sri Lanka, and Vietnam have been included for dengue whereas Burkina Faso has been included for malaria.",
      br(), br(),
      "2) Within each country,",
      strong ("enter the estimated costs per kilometer squared for each program phase"), 
      "(planning, preparation, production, distribution, release, and monitoring)",
      br(), br(),
      "3)",
      strong("Select an estimated effectiveness of the intervention"), 
      "from 0-100% effective.",
      br(), br(),
      "4) ",
      strong("Click Submit. "),
      "Based on these inputs and the secondary inputs (i.e., population, disease burden, area, etc.) the tool will estimate several outputs and outcomes: ",
      br(), br(),
      "Cost outcomes are reported for the smallest geographic  unit in each country and include: total annual program cost, cost per person covered by the intervention, and 10-year scale up cost.",
      br(), br(),
      "Benefit outcomes include the total cases, Disability Adjusted Life-Years (DALYs), ambulatory visits, hospitalized visits, and deaths averted by the intervention in each geography. The cost per case averted, cost per Disability Adjusted Life Year (DALY) averted, cost per death averted, health system costs averted, and economic costs averted are also reported.",
      br(),
      h1("Contact Information"),
      "Aldina Mesic (amesic@uw.edu), William Sheahan (wsheahan@uw.edu)",
      br(),
      "Jairam Lingappa (lingappa@uw.edu), The START Center (start@uw.edu)"
    )
  )
}
